version: "3"

services:
    nginx:
        image: "nginx:latest"
        ports: 
            - "80:80"
        volumes: 
            - ./nginx:/etc/nginx
            - ./www:/www
    redis:
      image: redis:6.0
      volumes: 
        - ./volume/redis/data:/data
      ports: 
        - "6379:6379"